#!/bin/bash

docker build --platform linux/amd64,linux/arm64 -t promovaweb/n8n-community-nodes:latest -f latest/Dockerfile .

docker build --platform linux/amd64,linux/arm64 -t promovaweb/n8n-community-nodes:next -f next/Dockerfile .

docker push promovaweb/n8n-community-nodes:latest

docker push promovaweb/n8n-community-nodes:next

